spring:
  application:
    name: gateway-api
  #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
#  cloud:
#    gateway:
#      routes:
#        id: host_losy
#        uri: http:www.baidu.com
#        predicates:
#          - path: /zgg/** # 请求路径待zgg 转发
#

server:
  port: 8090
