spring:
  application:
    name: gateway-api
  #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: aaa
        uri: http://localhost:9090
        predicates:
          - Path=/helloword/**
        filters:
          - StripPrefix=1 # helloword 转发


server:
  port: 8090
